from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from typing import List, Optional
from ..models.inventory import Inventory
from ..models.product import Product
from ..database import get_db
from ..schemas.cart import CartItemCreate, CartItemUpdate, CartItemResponse
from ..models.cart import CartItem
from ..models.user import User
from ..services.auth import get_current_user

router = APIRouter(prefix="/cart", tags=["Cart"])


@router.get("", response_model=List[CartItemResponse])
def get_cart(
    db: Session = Depends(get_db),
    current_user: Optional[User] = Depends(get_current_user)
):
    # If no user logged in, return empty cart
    if not current_user:
        return []
    
    cart_items = db.query(CartItem).filter(
        CartItem.user_id == current_user.id
    ).all()
    return cart_items


@router.post("", response_model=CartItemResponse, status_code=200)
def add_to_cart(
    item_data: CartItemCreate,
    current_user: Optional[User] = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    # Must be authenticated to add to cart
    if not current_user:
        raise HTTPException(status_code=401, detail="Authentication required")
    
     # Validate inventory
    inventory = db.query(Inventory).filter(
        Inventory.product_id == item_data.product_id
    ).first()
    
    # Validate price from database (security fix)
    product = db.query(Product).filter(Product.id == item_data.product_id).first()
    if not product:
        raise HTTPException(status_code=404, detail="Product not found")
    
    # Use price from database, not from client
    actual_price = product.current_price

    if inventory and inventory.quantity_on_hand < item_data.quantity:
        raise HTTPException(
            status_code=400, 
            detail=f"Insufficient stock. Available: {inventory.quantity_on_hand}"
        )
    
    # Check if item already exists in cart
    existing_item = db.query(CartItem).filter(
        CartItem.user_id == current_user.id,
        CartItem.product_id == item_data.product_id,
        CartItem.color == item_data.color
    ).first()
    
    if existing_item:
        # Update quantity
        existing_item.quantity += item_data.quantity
        db.commit()
        db.refresh(existing_item)
        return existing_item
    
    # Create new cart item (id will be auto-generated by MySQL)
    new_item = CartItem(
        user_id=current_user.id,
        product_id=item_data.product_id,
        product_item_id=item_data.product_item_id,
        name=item_data.name,
        img=item_data.img,
        color=item_data.color,
        quantity=item_data.quantity,
        price=actual_price
    )
    
    db.add(new_item)
    db.commit()
    db.refresh(new_item)
    return new_item


@router.patch("/{item_id}", response_model=CartItemResponse)
def update_cart_item(
    item_id: int,
    item_update: CartItemUpdate,
    current_user: Optional[User] = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    # Must be authenticated to update cart
    if not current_user:
        raise HTTPException(status_code=401, detail="Authentication required")
    
    cart_item = db.query(CartItem).filter(
        CartItem.id == item_id,
        CartItem.user_id == current_user.id
    ).first()
    
    if not cart_item:
        raise HTTPException(status_code=404, detail="Cart item not found")
    
    cart_item.quantity = item_update.quantity
    db.commit()
    db.refresh(cart_item)
    return cart_item


@router.delete("/{item_id}", status_code=200)
def remove_from_cart(
    item_id: int,
    current_user: Optional[User] = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    # Must be authenticated to remove from cart
    if not current_user:
        raise HTTPException(status_code=401, detail="Authentication required")
    
    cart_item = db.query(CartItem).filter(
        CartItem.id == item_id,
        CartItem.user_id == current_user.id
    ).first()
    
    if not cart_item:
        raise HTTPException(status_code=404, detail="Cart item not found")
    
    db.delete(cart_item)
    db.commit()
    return {"message": "Item removed from cart"}
